### ISSUE TITLE
LuaBlueprintFunctionLibrary.cpp Line 337

### ISSUE THREAD

**Issue by bradyrussell** [rdeioris/LuaMachine#10]
When working on my fork of this awesome project I found something that seems off on this line:

https://github.com/rdeioris/LuaMachine/blob/7a7331569c033672250f6a1e28f309ed12fa26ab/Source/LuaMachine/Private/LuaBlueprintFunctionLibrary.cpp#L337

It makes more sense to me that this should be

`if (Value.Type != ELuaValueType::Thread || !Value.LuaState)`

As it is currently the function will always return invalid if the LuaState is valid.

**Comment by rdeioris** [comment]
Thanks! you are absolutely right. Fixed and enqueued for marketplace.
