### ISSUE TITLE
UE5: Couldn't build on linux as PlatformFilemanager.h was renamed

### ISSUE THREAD

**Issue by asusha94** [rdeioris/LuaMachine#39]
Hi

I've added the plugin into my project but it can't be compiled:

```
Plugins/LuaMachine/Source/LuaMachine/Private/LuaBlueprintFunctionLibrary.cpp:15:10: fatal error: 'HAL/PlatformFilemanager.h' file not found
#include "HAL/PlatformFilemanager.h"
```

I've found that the file has a new name in UE5: `HAL/PlatformFileManager.h`. I suppose building projects is not affected on Windows as its filesystem is case insensitive.

Here is a possible fix. I couldn't make a pull request myself.

```c++
#if !defined(ENGINE_MAJOR_VERSION) || ENGINE_MAJOR_VERSION < 5
#include "HAL/PlatformFilemanager.h"  // UE4
#else
#include "HAL/PlatformFileManager.h"  // UE5
#endif
```

It works with UE5 but I haven't tested with UE4 (maybe there is no need in `!defined(ENGINE_MAJOR_VERSION)` part).

Could someone add this? Thanks

**Comment by Olathuss** [comment]
That is the exact same include file for both cases... the result is exactly the same as it is now:

`#include "HAL/PlatformFilemanager.h"`

I haven't had this issue with UE5. Are you sure the issue wasn't with something else?

**Comment by Olathuss** [comment]
Sorry, didn't catch the "M" being lowercase in one and upper in the other. Looks like it has been updated to use the updated header.

**Comment by knapsu** [comment]
No, it has not been fixed. I've created a pull request.
