### ISSUE TITLE
Ｑ: is possible to create an animation sequence with LuaMachine like c++? 

### ISSUE THREAD

**Issue by eggcaker** [rdeioris/LuaMachine#45]
is possible to create an animation sequence with LuaMachine like c++, to allow blueprint to use ? 
any document about if yes ?

**Comment by rdeioris** [comment]
If you mean calling lua from animation blueprints this is doable, if you mean something else you should provide more details, but in any case if you can do something in c++ you can expose it to lua

**Comment by eggcaker** [comment]
I want to use lua to do same thing before should be in c++ ,  not expose function from c++.

**Comment by Olathuss** [comment]
You have to expose a function from C/C++ in order to use it with LUA. And if you can do it in C++ with Unreal, then you can do it with LUA by exposing it.
