### ISSUE TITLE
Missing includes when packaging plugin but does not affect source build

### ISSUE THREAD

**Issue by Astaelan** [rdeioris/LuaMachine#52]
Reproduction:
- Create new empty C++ project (such as HostProject, just don't call it LuaMachine, cannot have a module with same name as project)
- Clone LuaMachine into `<Project>/Plugins/LuaMachine`
- Refresh VS Project files to include LuaMachine source
- Open VS and `Rebuild Solution`, everything builds correctly (usually, sometimes had heap allocation failures with 64GB of ram)
- Open plugin browser, press `Package` on the plugin
- Fails due to 2 files missing `ENGINE_MAJOR_VERSION` macros

Solution:
- Add `#include "Runtime/Launch/Resources/Version.h"` to `LuaCommandExecutor.h` and `LuaMultiLineEditableTextBox.h` immediately before any generated headers (LuaMultiLineEditableTextBox has a generated header, put this include before it)

Git Diff (didn't feel like forking for a 2 line PR):
```
diff --git a/Source/LuaMachine/Public/LuaCommandExecutor.h b/Source/LuaMachine/Public/LuaCommandExecutor.h
index 6956cb5..8864a5c 100644
--- a/Source/LuaMachine/Public/LuaCommandExecutor.h
+++ b/Source/LuaMachine/Public/LuaCommandExecutor.h
@@ -5,6 +5,7 @@
 #include "CoreMinimal.h"
 #include "HAL/IConsoleManager.h"
 #include "Framework/Commands/InputChord.h"
+#include "Runtime/Launch/Resources/Version.h"

 class ULuaState;

diff --git a/Source/LuaMachine/Public/LuaMultiLineEditableTextBox.h b/Source/LuaMachine/Public/LuaMultiLineEditableTextBox.h
index 6661fcd..96a9ad2 100644
--- a/Source/LuaMachine/Public/LuaMultiLineEditableTextBox.h
+++ b/Source/LuaMachine/Public/LuaMultiLineEditableTextBox.h
@@ -5,6 +5,7 @@
 #include "CoreMinimal.h"
 #include "Components/TextWidgetTypes.h"
 #include "Components/MultiLineEditableTextBox.h"
+#include "Runtime/Launch/Resources/Version.h"
 #include "LuaMultiLineEditableTextBox.generated.h"

 USTRUCT(BlueprintType)
```

**Comment by Olathuss** [comment]
Which version of Unreal are you using? Are you using a source build?

**Comment by Astaelan** [comment]
I think it was 5.1.x, it's been a few months so I can't be certain at this point.

**Comment by Olathuss** [comment]
Yup, can confirm was able to replicate the issue.

**Comment by Olathuss** [comment]
Do you want to submit your fix as a pull request?

**Comment by Astaelan** [comment]
It's been a while, I don't think I have the actual code kicking around anymore (recent PC crash, new PC, lost some local work).
But I at least had the foresight to post the diff above, feel free to apply it and make a new PR per your preferred workflow.
