### ISSUE TITLE
Issues with UTF-8 processing and rendering

### ISSUE THREAD

**Issue by mp-pinheiro** [rdeioris/LuaMachine#69]
Hey! As always, great plugin, it's basically the backbone of our game.

We've been facing this issue for a while now, but got away with workarounds so far. 

We're having issues with how LuaMachine and Unreal communicate UTF-8 strings that contain Simplified Chinese characters.

Here's an example:

```lua
local t = "土豆"
print(t)
```

This is what is printed to Unreal's log:

```
F
```

The same happens if I set a string in Unreal to "土豆", then pass it to LuaState as a LuaValue using the `String to Lua Value` blueprint method and print it in the Lua script. Like this:

![image](https://github.com/user-attachments/assets/a89a36da-365a-4acd-8f49-58dee0b4396a)

```
local t = UE_getT()
print(t)
```

Same result: 

```
F
```

I also tried this:

![image](https://github.com/user-attachments/assets/953f4bf5-8652-48c1-a46d-c78aa73ea19c)

And the result changes to, instead of printing `F`, it prints this:

```
??????
```

It really seems like information is being lost given `土豆` is a 6 byte sequence, while `F` is 2 bytes. The `??????` response is also 6 bytes, which is promissing, but still the info seems to just have been replaced with question mark characters.

Any light you could shine our way? We're on Unreal 4.25.

Thanks and thanks a lot for the plugin!

Edit: Also, I'm not really sure if this is a LuaMachine or a straight up Lua limitation. I've seen some other people struggle with Chinese on some forum threads, but all I could find were recommendations of utf-8 libraries. So yeah, if this is a Lua thing do let us know! We'd love to find a solution.

**Comment by rdeioris** [comment]
Hi @mp-pinheiro the main issue here is that there are 3 systems competing:

* lua (ANSI c strings)
* your system (from the code you pasted it is set as UTF8)
* unreal (UTF16)

The default print (that you are free to override) expects simple lua strings (ansi C) as input, so if you want a version "understanding" UTF8 you can do something like this:

![image](https://github.com/user-attachments/assets/e0456e13-2ae4-4604-adde-58bf951d0fe4)

**Comment by mp-pinheiro** [comment]
Oh I see! That does make a lot of sense.

Thanks for the response, I think we can get it working with this!
