### ISSUE TITLE
Is there a way to get the actual table reference string?

### ISSUE THREAD

**Issue by mp-pinheiro** [rdeioris/LuaMachine#9]
Hi! First of all, amazing plugin!

When casting a table to string and printing I get something like `table: 5`, which appears to be the registry entry id of the table, which is changeable, if I understand this correctly. 

Is there a way to get the `table: 00AFA376` string? I have a table indexed table that I'm trying to reflect as a String to Blueprint map.

Thanks again!

**Comment by rdeioris** [comment]
Hi, thanks for the suggestion, indeed accessing low-level pointers could be a really useful feature.
Please clone the lastest master, you will find two new functions: LuaValueToPointer (returns int64) and LuaValueToHexPointer (returns FString).

**Comment by mp-pinheiro** [comment]
This is perfect! Thanks a lot for the swift response and even swifter feature implementation!
